name: 'ClickHouse Server Action'
description: 'A docker container action for running ClickHouse server to run tests or simple actions'
author: 'Praneeth Kumar Reddy (praneeth527)'

branding:
  icon: 'database'
  color: 'yellow'

inputs:
  # See https://hub.docker.com/r/clickhouse/clickhouse-server/tags for supported versions
  tag:
    description: 'ClickHouse docker image tag to run'
    required: false
    default: 'latest-alpine'

runs:
  using: 'docker'
  image: 'Dockerfile'